In [9]:
import numpy as np
from scipy import stats
rng = np.random.default_rng()
sample1 = stats.uniform.rvs(size=100, random_state=rng)
sample2 = stats.norm.rvs(size=110, random_state=rng)
response=stats.ks_2samp(sample1, sample2)

In [3]:
sample1

array([0.34126091, 0.05671718, 0.85755738, 0.64328599, 0.06293401,
       0.40272922, 0.47836305, 0.08639204, 0.2536428 , 0.07013727,
       0.13526335, 0.6542698 , 0.05105211, 0.44176002, 0.19790927,
       0.4822496 , 0.65721936, 0.55698141, 0.12004974, 0.1885385 ,
       0.15079322, 0.96704546, 0.16136581, 0.88404033, 0.55671821,
       0.55712692, 0.25002952, 0.99307076, 0.27496942, 0.69272401,
       0.31767796, 0.4789675 , 0.79336035, 0.48920609, 0.69440722,
       0.4771389 , 0.77710642, 0.01976161, 0.04658293, 0.15910874,
       0.59690739, 0.16926976, 0.70500556, 0.24359974, 0.05336247,
       0.88733207, 0.87325589, 0.89943844, 0.71232645, 0.48150449,
       0.93965169, 0.6845731 , 0.28058444, 0.81687649, 0.42074227,
       0.58280193, 0.07144425, 0.74047606, 0.51086709, 0.27939357,
       0.72721096, 0.87201329, 0.54194669, 0.79363669, 0.68694813,
       0.10070581, 0.63915529, 0.84743958, 0.24755721, 0.27383427,
       0.74353087, 0.7051888 , 0.38201586, 0.66816563, 0.20173

In [4]:
sample2

array([-7.76106444e-01,  2.14690159e-01, -7.13244040e-01,  1.56397140e+00,
        1.22437135e+00,  6.33602173e-01, -1.77954621e+00,  1.01226333e-01,
       -2.13490750e+00, -1.36466124e-03,  3.92530291e-01, -1.31231640e+00,
       -1.43905090e+00, -1.18858869e+00,  1.54288166e-01, -6.04952963e-01,
        3.83504068e-01,  1.66151430e+00,  1.00914438e+00,  8.83416689e-01,
       -1.74300001e+00,  1.11871145e+00, -2.10566729e+00, -6.91497351e-01,
       -1.23558854e+00,  6.13841025e-01, -1.05550961e+00, -9.94493938e-01,
        7.56442162e-01,  1.33182491e+00,  1.49891105e+00, -1.29977154e+00,
       -8.48500872e-01, -4.68530305e-01,  2.02897152e-01,  7.57845632e-01,
       -4.13684766e-01, -1.88665486e+00,  5.76673176e-01, -1.44404397e+00,
        5.98944913e-01,  3.73205581e-01, -1.92663632e+00,  2.08503820e-01,
       -1.10106142e-01,  1.90822089e-01, -7.26858624e-01,  2.68302283e+00,
       -1.22184312e+00, -3.19410830e-01,  7.04255055e-01, -3.36486525e+00,
       -2.16696328e+00, -

In [16]:
response.pvalue ## if p value  greater than 0.5 thet data have good relation or fromsame distribuction

4.351893101922804e-11

In [17]:
round(response.pvalue)

0

In [15]:
round(response.pvalue,10)

0.0

In [18]:
# #Anomly in my dataset

# #1.High Null Value
# ##2.Missing columns
# #OUTLIER 
# #cATEROCIAL :
# Gender --. MALE ,FEMALE ,OTHER


In [20]:
import pandas as pd


In [22]:
df=pd.read_csv("/config/workspace/artifact/12122022__195112/data_ingestion/dataset/train.csv")

In [23]:
df.isnull().sum()

class         0
aa_000        0
ab_000    22338
ac_000     1748
ad_000     7438
          ...  
ee_007      305
ee_008      305
ee_009      305
ef_000     1412
eg_000     1411
Length: 171, dtype: int64

In [25]:
(df.isnull().sum()/df.shape[0]).values

array([0.        , 0.        , 0.77160622, 0.06037997, 0.25692573,
       0.04500864, 0.04500864, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01056995, 0.01053541, 0.01053541,
       0.07765112, 0.01067358, 0.01053541, 0.01067358, 0.00977547,
       0.01067358, 0.00977547, 0.04873921, 0.01053541, 0.01053541,
       0.01053541, 0.04504318, 0.04507772, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01053541, 0.01053541,
       0.01053541, 0.01053541, 0.01053541, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01070812, 0.01070812,
       0.01070812, 0.01070812, 0.01070812, 0.01056995, 0.04880829,
       0.04884283, 0.04511226, 0.04500864, 0.01067358, 0.01067358,
       0.00977547, 0.00977547, 0.38093264, 0.44981002, 0.65354

In [26]:
df.isnull().sum()/df.shape[0]

class     0.000000
aa_000    0.000000
ab_000    0.771606
ac_000    0.060380
ad_000    0.256926
            ...   
ee_007    0.010535
ee_008    0.010535
ee_009    0.010535
ef_000    0.048774
eg_000    0.048739
Length: 171, dtype: float64

In [33]:
drop_column_names=[]
for column_name,missing_percentage in zip((df.isnull().sum()/df.shape[0]).index,(df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage*100)
    if missing_percentage>0.3:
        drop_column_names.append(column_name)

class 0.0
aa_000 0.0
ab_000 77.16062176165804
ac_000 6.037996545768567
ad_000 25.692573402417963
ae_000 4.500863557858376
af_000 4.500863557858376
ag_000 1.0535405872193437
ag_001 1.0535405872193437
ag_002 1.0535405872193437
ag_003 1.0535405872193437
ag_004 1.0535405872193437
ag_005 1.0535405872193437
ag_006 1.0535405872193437
ag_007 1.0535405872193437
ag_008 1.0535405872193437
ag_009 1.0535405872193437
ah_000 1.0569948186528497
ai_000 1.0535405872193437
aj_000 1.0535405872193437
ak_000 7.76511226252159
al_000 1.067357512953368
am_0 1.0535405872193437
an_000 1.067357512953368
ao_000 0.9775474956822107
ap_000 1.067357512953368
aq_000 0.9775474956822107
ar_000 4.8739205526770295
as_000 1.0535405872193437
at_000 1.0535405872193437
au_000 1.0535405872193437
av_000 4.504317789291883
ax_000 4.507772020725389
ay_000 1.0535405872193437
ay_001 1.0535405872193437
ay_002 1.0535405872193437
ay_003 1.0535405872193437
ay_004 1.0535405872193437
ay_005 1.0535405872193437
ay_006 1.0535405872193437
ay_0

In [34]:
drop_column_names

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [35]:
df.isna().sum()/df.shape[0]>0.03

class     False
aa_000    False
ab_000     True
ac_000    False
ad_000    False
          ...  
ee_007    False
ee_008    False
ee_009    False
ef_000    False
eg_000    False
Length: 171, dtype: bool

In [36]:
null_report=df.isna().sum()/df.shape[0]
null_report[null_report>0.3].index


In [38]:
null_report[null_report>0.3].index

Index(['ab_000', 'bk_000', 'bl_000', 'bm_000', 'bn_000', 'bo_000', 'bp_000',
       'bq_000', 'br_000', 'cr_000'],
      dtype='object')

In [47]:
df.iloc[:,[0]].drop("class",axis=1).columns


Index([], dtype='object')

In [48]:
len(df.iloc[:,[0]].drop("class",axis=1).columns)

0